### ISSUE TITLE
Handle when user inputs "free" to mean 0

### ISSUE THREAD

**Issue by walter** [theocodes/monetized#19]
Thanks for a very useful package.

We're using the `Money` type to track the price of an item. Sometimes the user indicates that there isn't a price by entering "free" which throws an error (see below). We've worked around this by using 0 as the value for the item and trying to steer our users to enter that.

However, it would be nice if the Money type handled casting "free" to 0 for us.

Here's the error:

```Elixir
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in List.first/1
        (elixir) lib/list.ex:163: List.first(nil)
        lib/money.ex:271: Monetized.Money.from_string/2
        lib/money.ex:79: Monetized.Money.cast/1
        (ecto) lib/ecto/type.ex:564: Ecto.Type.cast/2
        (ecto) lib/ecto/changeset.ex:453: Ecto.Changeset.cast_field/6
        (ecto) lib/ecto/changeset.ex:412: Ecto.Changeset.process_param/7
        (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (ecto) lib/ecto/changeset.ex:384: Ecto.Changeset.do_cast/7
```

**Comment by theocodes** [comment]
Hi @walter,

Glad you find monetized useful and you're welcome ;)
Sorry for taking so long to get back to you - I took some time off and just recently got back.

I've given some thought to your suggestion however, I think the idea of "free" doesn't really belong in the money itself but rather on what's being sold. `Money` is meant to represent a type of value that happens to carry a currency along with it, and adding the concept of "free" feels to me as out of scope.

Hope this makes sense?
If not, i'm happy to discuss :)

Have a great weekend!

**Comment by walter** [comment]
I'm ok with not handling "free", but I wonder whether this particular code should handle non-matches more elegantly. Meaningful exception maybe? Not sure.

**Comment by theocodes** [comment]
So what is the behaviour you're getting at the moment? 

`Money.from_string("free")` raises the error above?

hmm, I agree that the error could be handled more elegantly.. Will make a note of that for the next update.

Thanks 👍

**Comment by walter** [comment]
Yep, that's the error I get.

That would be cool. Thanks!
